version: "3.9"

services:
  app:
    container_name: node-app
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"